### ISSUE TITLE
Titles should be more descriptive

### ISSUE THREAD

**Issue by fceruti** [ash-project/ash_tutorial#3]
Right now notebook titles are "Aggregates", "API", "Attributes" and such.

The problem is that if you use other notebooks, it's really easy to get lost on what's inside a particular document when looking at the list.

I propose to do something very similar to what the guys at ESCT did with their nomenclature. 

<img width="1045" alt="Screenshot 2023-10-05 at 17 29 07" src="https://github.com/ash-project/ash_tutorial/assets/250665/5b08bef5-a9e2-4cee-b015-d4f57e5a8d65">

**Comment by woutdp** [comment]
Good point, I've added `Ash: "number" - ` to the titles
