### ISSUE TITLE
Notebook 6, Attributes - Missing domain

### ISSUE THREAD

**Issue by aidalgol** [ash-project/ash_tutorial#9]
The `Tutorial.Support.Ticket` module is missing a domain.  This produces only a warning when evaluating the cell that defines this module, but produces an error in the next step, "Creating a Ticket".
```console
** (ArgumentError) Could not determine domain for changeset. Provide the `domain` option or configure a domain in the resource directly.
```
Adding `domain: Tutorial.Support` to the `use Ash.Resource` resolves both the warning and error.

**Comment by woutdp** [comment]
Thank you!
